cargo-features = ["per-package-target"]

[workspace]
members = [
    "chainloader",
   # "chainload-app",
    "client",
]
default-members = ["chainloader"]
resolver = "2"

[profile.release]
debug = true
opt-level = 's'
lto = true
