cargo-features = ["per-package-target"]

[workspace]
members = [
    "picopif",
]
resolver = "2"

[profile.release]
debug = true
opt-level = 's'
codegen-units=1
lto = true

[profile.dev]
opt-level = 1
