[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "elf2uf2-rs -d -s"
runner = "probe-rs run --chip RP2040 --protocol swd "

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"
# Override these in $CARGO_HOME/config.toml
#WIFI_NETWORK = "network"
#WIFI_PASSWORD = "password"
